import { createClient, type RealtimeChannel, type SupabaseClient } from '@supabase/supabase-js'

const url=import.meta.env.VITE_SUPABASE_URL?.trim()
const anonKey=import.meta.env.VITE_SUPABASE_ANON_KEY?.trim()
export const onlineConfigured=Boolean(url&&anonKey)
export const supabase:SupabaseClient|null=onlineConfigured?createClient(url!,anonKey!,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}):null

export type RoomStatus='lobby'|'playing'|'closed'
export interface OnlineRoom{id:string;code:string;host_id:string;status:RoomStatus;max_players:number;shared_state:Record<string,unknown>;state_version:number;created_at:string;updated_at:string}
export interface OnlineMember{id:string;room_id:string;user_id:string;display_name:string;hero_id?:string;ready:boolean;joined_at:string;last_seen:string}
export interface RoomEvent{id:number;room_id:string;user_id:string;event_type:string;payload:Record<string,unknown>;sequence:number;created_at:string}

export async function ensureOnlineUser(){if(!supabase)throw new Error('Supabase não configurado.');const current=await supabase.auth.getSession();if(current.data.session?.user)return current.data.session.user;const result=await supabase.auth.signInAnonymously();if(result.error)throw result.error;if(!result.data.user)throw new Error('Não foi possível iniciar a sessão online.');return result.data.user}
export function normalizeRoomCode(value:string){return value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6)}
export async function createOnlineRoom(displayName:string,heroId?:string){if(!supabase)throw new Error('Supabase não configurado.');const user=await ensureOnlineUser();const result=await supabase.rpc('create_coop_room',{p_display_name:displayName.trim().slice(0,24)||'Aventureiro',p_hero_id:heroId??null});if(result.error)throw result.error;return{...(result.data as {room_id:string;room_code:string}),user_id:user.id}}
export async function joinOnlineRoom(code:string,displayName:string,heroId?:string){if(!supabase)throw new Error('Supabase não configurado.');const user=await ensureOnlineUser();const result=await supabase.rpc('join_coop_room',{p_code:normalizeRoomCode(code),p_display_name:displayName.trim().slice(0,24)||'Aventureiro',p_hero_id:heroId??null});if(result.error)throw result.error;return{...(result.data as {room_id:string;room_code:string}),user_id:user.id}}
export async function leaveOnlineRoom(roomId:string){if(!supabase)return;const result=await supabase.rpc('leave_coop_room',{p_room_id:roomId});if(result.error)throw result.error}
export async function setMemberReady(roomId:string,ready:boolean,heroId?:string){if(!supabase)return;const user=await ensureOnlineUser();const result=await supabase.from('coop_room_members').update({ready,hero_id:heroId??null,last_seen:new Date().toISOString()}).eq('room_id',roomId).eq('user_id',user.id);if(result.error)throw result.error}
export async function loadOnlineRoom(roomId:string){if(!supabase)throw new Error('Supabase não configurado.');const [room,members]=await Promise.all([supabase.from('coop_rooms').select('*').eq('id',roomId).single(),supabase.from('coop_room_members').select('*').eq('room_id',roomId).order('joined_at')]);if(room.error)throw room.error;if(members.error)throw members.error;return{room:room.data as OnlineRoom,members:members.data as OnlineMember[]}}
export async function publishRoomState(roomId:string,state:Record<string,unknown>,expectedVersion:number){if(!supabase)throw new Error('Supabase não configurado.');const result=await supabase.rpc('update_coop_room_state',{p_room_id:roomId,p_state:state,p_expected_version:expectedVersion});if(result.error)throw result.error;return result.data as number}
export async function publishRoomEvent(roomId:string,eventType:string,payload:Record<string,unknown>={}){if(!supabase)throw new Error('Supabase não configurado.');const result=await supabase.rpc('append_coop_event',{p_room_id:roomId,p_event_type:eventType,p_payload:payload});if(result.error)throw result.error;return result.data as number}
export function subscribeToOnlineRoom(roomId:string,onChange:()=>void,onPresence:(users:Record<string,unknown[]>)=>void):RealtimeChannel|null{if(!supabase)return null;const channel=supabase.channel(`coop:${roomId}`,{config:{presence:{key:'player'}}}).on('postgres_changes',{event:'*',schema:'public',table:'coop_rooms',filter:`id=eq.${roomId}`},onChange).on('postgres_changes',{event:'*',schema:'public',table:'coop_room_members',filter:`room_id=eq.${roomId}`},onChange).on('postgres_changes',{event:'INSERT',schema:'public',table:'coop_room_events',filter:`room_id=eq.${roomId}`},onChange).on('presence',{event:'sync'},()=>onPresence(channel.presenceState())).subscribe(async status=>{if(status==='SUBSCRIBED'){const user=await ensureOnlineUser();await channel.track({user_id:user.id,online_at:new Date().toISOString()})}});return channel}
export async function unsubscribeFromOnlineRoom(channel:RealtimeChannel|null){if(channel&&supabase)await supabase.removeChannel(channel)}

export interface CampaignSyncRow{id:string;user_id:string;hero_id:string|null;snapshot:Record<string,unknown>;updated_at:string}
export async function signUpWithEmail(email:string,password:string){if(!supabase)throw new Error('Supabase não configurado.');const result=await supabase.auth.signUp({email:email.trim(),password});if(result.error)throw result.error;return result.data}
export async function signInWithEmail(email:string,password:string){if(!supabase)throw new Error('Supabase não configurado.');const result=await supabase.auth.signInWithPassword({email:email.trim(),password});if(result.error)throw result.error;return result.data}
export async function signOutUser(){if(!supabase)return;await supabase.auth.signOut()}
export async function signInWithGoogle(){if(!supabase)throw new Error('Supabase não configurado.');const result=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin+window.location.pathname}});if(result.error)throw result.error;return result.data}
export async function requestPasswordReset(email:string){if(!supabase)throw new Error('Supabase não configurado.');const result=await supabase.auth.resetPasswordForEmail(email.trim());if(result.error)throw result.error}
export async function fetchPlayerCampaigns(userId:string){if(!supabase)return [] as CampaignSyncRow[];const result=await supabase.from('player_campaigns').select('*').eq('user_id',userId);if(result.error)throw result.error;return (result.data??[]) as CampaignSyncRow[]}
export async function upsertPlayerCampaign(userId:string,id:string,heroId:string|undefined,snapshot:Record<string,unknown>){if(!supabase)return;const result=await supabase.from('player_campaigns').upsert({id,user_id:userId,hero_id:heroId??null,snapshot});if(result.error)throw result.error}
export async function deletePlayerCampaigns(userId:string,ids:string[]){if(!supabase||!ids.length)return;const result=await supabase.from('player_campaigns').delete().eq('user_id',userId).in('id',ids);if(result.error)throw result.error}
